wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1677103935.778525
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: MLP[18,128,16,64,1]
data cleaning:
  desc: null
  value: None
dataset:
  desc: null
  value: Kaggle S3E7
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
